name: Deploy
run-name: sparkle server deploy running deploy stage 🚀
on:
  push:
    branches:
      - develop
      - master 
  pull_request:
    branches:
      - develop
      - master 
jobs:
  Run-Project_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout git repository
        uses: actions/checkout@v4
      - name: build the docker image
        run: docker-compose -f ./docker-compose.yaml build
      - name: login to aliyun docker repository
        run: docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} ${{ secrets.ALIYUN_REGISTRY }}
      - name: push image to aliyun docker repository
        run: docker-compose -f ./docker-compose.yaml push
      - name: update docker image and restart remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /opt/docker/config
            docker-compose -f ./docker-compose-sparkle-server.yml down
            docker-compose -f ./docker-compose-sparkle-server.yml pull 
            docker-compose -f ./docker-compose-sparkle-server.yml up -d
